### ISSUE TITLE
Layout site to match prototypes

### ISSUE THREAD

**Issue by wshanaa** [OSC-CSC480SP16/roots-GUI#1]
Layouts need to become finalized, along with colors and start working on page implementing working pages from the page mock ups.

There is also an issue with where the text from the form fields gets moved to just underneath the fields not working correctly with the bio area of the profile page.

**Comment by Stultz-e** [comment]
Let me know if we should test the sign up page or wait until it's more loyal to the mock ups. Thanks

**Comment by mcanale4** [comment]
4-6 hours
