### ISSUE TITLE
Display all errors in a consistent style

### ISSUE THREAD

**Issue by wshanaa** [OSC-CSC480SP16/roots-GUI#13]

**Comment by ecshafer** [comment]
What does this even mean?

**Comment by wshanaa** [comment]
The notifications that prompt a user that they have there is an issue with their submission should all be in the same style. There are ones in already in the login page that display when a person didn't enter in a field or when the email is not in the correct format. All other notifications should be presented in the same manner so when we do styling on the page it is easier to modify and provide a consistent user experience.

**Comment by wshanaa** [comment]
5hrs. Expanded on error messages and added additional restrictions to the current form fields and made sure they work with the major browsers.
